name: fr0gsite
description: Free Open-Source Plattform with a self managing community.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.5.8

environment:
  sdk: 3.9.2
  flutter: 3.35.5

dependencies:
  flutter:
    sdk: flutter

  #Storage
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^10.0.0-beta.4
  path_provider: ^2.0.11 #No Web support

  #Accessbility
  google_fonts: ^6.3.2
  share_plus: ^12.0.1
  cupertino_icons: ^1.0.2
  url_launcher: ^6.3.2
  mobile_scanner: ^7.1.2
  #font_awesome_flutter: ^9.1.0
  #share_plus: ^7.0.2 #Share content to other apps
  #auto_size_text: ^3.0.0 #Auto size text to fit in container https://pub.dev/packages/auto_size_text

  ##Internationalization
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  ##UI
  toggle_switch: ^2.0.1
  auto_size_text: ^3.0.0
  like_button: ^2.0.5
  file_picker: ^10.2.4
  percent_indicator: ^4.2.3
  elegant_notification: ^2.5.1
  settings_ui: ^2.0.2
  another_xlider: ^3.0.1 #for audio adjustment in postviewer
  action_slider: ^0.7.0
  fl_chart: ^1.1.1
  country_flags: ^4.1.0
  #easy_stepper: ^0.8.3
  easy_stepper:
    git:
      url: https://github.com/cubebased/easy_stepper.git
      ref: main
  searchfield: ^1.3.3
  
  #Animation
  lottie: ^3.3.2
  video_player: ^2.9.5 #Support only Mobile and Web. Todo find video_player for Windows
  video_thumbnail: ^0.5.3
  
  #Blockchain
  eosdart:
    git:
      url: https://github.com/cubebased/eosdart.git
      ref: master

  #Development
  flutter_launcher_icons: ^0.14.1
  #go_router: ^9.0.3 #Routing https://pub.dev/packages/go_router
  #device_info_plus: ^9.0.2 #Get device info https://pub.dev/packages/device_info_plus

  #Other
  provider: ^6.0.5
  fluro: ^2.0.5
  pointycastle: ^3.9.1
  universal_html: ^2.3.0
  package_info_plus: ^9.0.0 #Querying information about the application package
  #flutter_bloc: ^8.1.2
  http: ^1.5.0
  url_strategy: ^0.3.0
  blur: ^4.0.2
  qr_flutter: ^4.1.0
  audioplayers: ^6.5.1
  #universal_io: ^2.2.0
  #qr_code_scanner: ^1.0.1
  #geolocator 9.0.2 #Get user location for language selection


  convert: any
  http_parser: any
  image: any
  flutter_gen: ^5.11.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  integration_test:
    sdk: flutter
  test: any
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  #After changes in flutter_icons, generate icons with: dart run flutter_launcher_icons
  image_path: "assets/images/ic_launcher.png"
  #remove_alpha_ios: true

  android: true
  windows:
    generate: true
    icon_size: 48 # min:48, max:256, default: 48
  web:
    generate: true
#    background_color: "#hexcode"
#    theme_color: "#hexcode"
  macos:
    generate: true
  ios:
    generate: true
    #adaptive_icon_background: "#hexcode"
    #adaptive_icon_foreground: "#hexcode"

flutter:
  generate: true

  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/badge/
    - assets/images/ageverification/
    - assets/icons/
    - assets/fonts/
    - assets/sounds/
    - assets/frog/
    - assets/frogwebp/
    - assets/lottie/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
fonts:
  - family: BebasNeue-Regular
    fonts:
      - asset: assets/fonts/BebasNeue-Regular.ttf
      - weight: 800
  - family: Oxanium
    fonts:
      - asset: assets/fonts/Oxanium-VariableFont_wght.ttf
      - weight: 800
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
